export const TIPOS_EVENTO_FALLBACK = [
  {
    id: 1,
    nombre: 'XV',
    duracionMinutos: 360,
    duracionMaximaMinutos: 360,
    limpiezaMinutos: 60,
    precioBase: 0,
    color: '#8b5cf6',
    activo: true,
  },
  {
    id: 2,
    nombre: 'Casamiento',
    duracionMinutos: 480,
    duracionMaximaMinutos: 480,
    limpiezaMinutos: 90,
    precioBase: 0,
    color: '#ec4899',
    activo: true,
  },
  {
    id: 3,
    nombre: 'Cumpleanos',
    duracionMinutos: 240,
    duracionMaximaMinutos: 240,
    limpiezaMinutos: 45,
    precioBase: 0,
    color: '#f97316',
    activo: true,
  },
  {
    id: 4,
    nombre: 'Bautismo',
    duracionMinutos: 240,
    duracionMaximaMinutos: 240,
    limpiezaMinutos: 45,
    precioBase: 0,
    color: '#22c55e',
    activo: true,
  },
]
